import React from 'react';
import { Database, Activity } from 'lucide-react';

export default function DataBadge({ type = 'real' }) {
  if (type === 'real') {
    return (
      <span className="badge-real-data" title="Environmental data sourced conceptually from NCPOR">
        <Database className="w-3 h-3 mr-1 inline" />
        REAL DATA (NCPOR)
      </span>
    );
  }
  return (
    <span className="badge-simulated-data" title="Telemetry generated by digital twin simulation stream">
      <Activity className="w-3 h-3 mr-1 inline" />
      SIMULATED DATA
    </span>
  );
}
